cache: bundler
language: ruby

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e 'create database wherex_test;'; fi
  - if [[ "$DB" == "postgres" ]]; then psql -c 'create database wherex_test;' -U postgres; fi

rvm:
  - 2.0.0
  - 2.1.5
  - ruby-head

gemfile:
  - gemfiles/ar_3.1.gemfile
  - gemfiles/ar_3.2.gemfile
  - gemfiles/ar_4.0.gemfile
  - gemfiles/ar_4.1.gemfile
  - gemfiles/ar_4.2.gemfile

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/ar_4.2.gemfile

addons:
  code_climate:
    repo_token: cd0a2d249ae3b4ba63161597f985fedb01d208d2fece3da0ca3cce379c5bc3b8
