cache: bundler
language: ruby

before_script:
  - mysql -e 'create database wherex_test;'
  - psql -c 'create database wherex_test;' -U postgres

rvm:
  - 2.0.0
  - 2.1.5
  - ruby-head

gemfile:
  - gemfiles/activerecord_3.1.gemfile
  - gemfiles/activerecord_3.2.gemfile
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.2.gemfile

env:
  - RAILS_DB=sqlite
  - RAILS_DB=mysql
  - RAILS_DB=postgres

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

addons:
  code_climate:
    repo_token: cd0a2d249ae3b4ba63161597f985fedb01d208d2fece3da0ca3cce379c5bc3b8
